path:
  video_path: "D:\\Vid√©os FINALES\\Short 64 - Les secrets de l'algorithme Facebook et Instagram.mp4"
  temp_path: "temp.mp4"
  final_path: "final.mp4"
  transcript_path: "new_word_timestamps.txt"
  theme: classic